// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npgtfynfvtutoaznzqzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wZ3RmeW5mdnR1dG9hem56cXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDQyNDAsImV4cCI6MjA2NTkyMDI0MH0.b23ZmwjCkylv7qAk1tQsmhrmdLuGe9PIaRIeBfVfGk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);